import sharp from 'sharp'
import { getObject, putObject } from '../../lib/s3'
import { sendToSession } from '../../lib/websocket'
import type { PipelineInput, ProgressEvent } from '../../lib/types'

interface PrintPrepareInput extends PipelineInput {
  readonly filteredImages: readonly string[]
  readonly collageKey: string
  readonly caption?: string
  readonly sentiment?: string
  readonly sentimentScore?: number
}

interface PrintPrepareOutput extends PrintPrepareInput {
  readonly downloadKey: string
  readonly printKey: string
}

const PRINT_WIDTH = 576
const CLAYCODE_SIZE = 200

/** Floyd-Steinberg dithering on single-channel greyscale pixel data. */
const floydSteinbergDither = (pixels: Uint8Array, width: number, height: number): Uint8Array => {
  const data = new Float32Array(pixels)
  // eslint-disable-next-line @typescript-eslint/no-non-null-assertion -- bounds checked by caller
  const get = (i: number): number => data[i]!
  const add = (i: number, v: number): void => { data[i] = get(i) + v }

  for (let y = 0; y < height; y++) {
    for (let x = 0; x < width; x++) {
      const idx = y * width + x
      const oldPixel = get(idx)
      const newPixel = oldPixel < 128 ? 0 : 255
      data[idx] = newPixel
      const err = oldPixel - newPixel

      if (x + 1 < width) add(idx + 1, err * 7 / 16)
      if (y + 1 < height) {
        if (x > 0) add((y + 1) * width + (x - 1), err * 3 / 16)
        add((y + 1) * width + x, err * 5 / 16)
        if (x + 1 < width) add((y + 1) * width + (x + 1), err * 1 / 16)
      }
    }
  }

  const output = new Uint8Array(width * height)
  for (let i = 0; i < data.length; i++) {
    output[i] = Math.max(0, Math.min(255, Math.round(get(i))))
  }
  return output
}

const notify = async (sessionId: string, progress: number, message: string): Promise<void> => {
  const event: ProgressEvent = {
    type: 'statusUpdate',
    data: { sessionId, status: 'processing', step: 'dither', progress, message },
  }
  await sendToSession(sessionId, event).catch(() => undefined)
}

/** Fetch pre-rendered ClayCode image from S3 (generated by frontend). */
const fetchClaycodeImage = async (sessionId: string): Promise<Buffer | null> => {
  try {
    return await getObject(`claycode-images/${sessionId}.png`)
  } catch {
    console.warn('[print-prepare] No pre-rendered ClayCode image found, skipping')
    return null
  }
}

export const handler = async (event: PrintPrepareInput): Promise<PrintPrepareOutput> => {
  const { sessionId, collageKey, filter, downloadCode } = event

  await notify(sessionId, 60, '印刷データ準備中...')

  const collageBuffer = await getObject(collageKey)

  // Save download copy (カラー原本)
  const downloadKey = `downloads/${sessionId}.png`
  await putObject(downloadKey, collageBuffer)

  // コラージュのメタデータ取得（元の比率を保持）
  const collageMeta = await sharp(collageBuffer).metadata()
  const collageW = collageMeta.width
  const collageH = collageMeta.height
  if (!collageW || !collageH) throw new Error('Invalid collage image: missing dimensions')
  const collageRatio = collageH / collageW
  const printCollageHeight = Math.round(PRINT_WIDTH * collageRatio)

  // レイアウト計算: コラージュ(元比率) + 余白(20) + ClayCode(220 if present)
  const padding = 20
  const clayCodeHeight = downloadCode ? CLAYCODE_SIZE + padding : 0
  const totalHeight = printCollageHeight + padding + clayCodeHeight

  // Step 1: コラージュを白キャンバスに配置 → ディザリング（写真部分のみ）
  const photoLayoutBuffer = await sharp({
    create: {
      width: PRINT_WIDTH,
      height: totalHeight,
      channels: 3 as const,
      background: { r: 255, g: 255, b: 255 },
    },
  })
    .composite([{
      input: await sharp(collageBuffer).resize(PRINT_WIDTH, printCollageHeight).toBuffer(),
      left: 0,
      top: 0,
    }])
    .greyscale()
    .raw()
    .toBuffer()

  // Step 2: ディザリング（写真エリアのみ → ClayCode部分は白のまま）
  const dithered = floydSteinbergDither(
    new Uint8Array(photoLayoutBuffer),
    PRINT_WIDTH,
    totalHeight,
  )

  // Step 3: ディザリング済み画像をsharpに戻す
  let finalImage = sharp(Buffer.from(dithered), {
    raw: { width: PRINT_WIDTH, height: totalHeight, channels: 1 },
  }).png()

  // Step 4: ClayCode をディザリング後に合成（クリーンな白黒を維持）
  if (downloadCode) {
    const claycodeImage = await fetchClaycodeImage(sessionId)
    if (claycodeImage) {
      const resized = await sharp(claycodeImage)
        .resize(CLAYCODE_SIZE, CLAYCODE_SIZE, { fit: 'contain', background: { r: 255, g: 255, b: 255 } })
        .png()
        .toBuffer()
      const ditheredBuffer = await finalImage.toBuffer()

      finalImage = sharp(ditheredBuffer).composite([{
        input: resized,
        left: Math.floor((PRINT_WIDTH - CLAYCODE_SIZE) / 2),
        top: printCollageHeight + Math.floor(padding / 2),
      }])
    }
  }

  const printBuffer = await finalImage.png().toBuffer()

  const printKey = `print-ready/${sessionId}.png`
  await putObject(printKey, printBuffer)

  await notify(sessionId, 90, '印刷データ準備完了')

  const now = new Date()
  const dateStr = `${String(now.getFullYear())}.${String(now.getMonth() + 1).padStart(2, '0')}.${String(now.getDate()).padStart(2, '0')}`
  console.log('[print-prepare] receipt generated:', { sessionId, filter, downloadCode, dateStr, size: `${String(PRINT_WIDTH)}x${String(totalHeight)}` })

  return { ...event, downloadKey, printKey }
}
